paths:
  /moreTelescopes/{telName}/{param}/Versions:
    get:
      parameters:
        - in: query
          description: ""
          name: Versions
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
